version: '3'

services:
    app:
        container_name: elasticsearchmodule-web-1
        build:
            context: ./
        volumes:
            - .:/var/www/html
        ports:
            - "8082:80"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        networks:
            - laravel
        depends_on:
            - mysql
            - elasticsearch

    mysql:
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "root"
            MYSQL_DATABASE: "elastic"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
            - "3908:3306"
        volumes:
            - 'mysql8:/var/lib/mysql'
            - './db/init.sql:/docker-entrypoint-initdb.d/01init.sql'
            - './db/custom-init.sh:/docker-entrypoint-initdb.d/02custom-init.sh'
        networks:
            - laravel

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8  # Updated version
        environment:
            - discovery.type=single-node
        ports:
            - "9208:9200"
        networks:
            - laravel

    kibana:
        image: docker.elastic.co/kibana/kibana:7.17.8  # Matching Elasticsearch version
        ports:
            - "56000:5601"
        depends_on:
            - elasticsearch
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    mysql8:
        driver: local
